name: Test and Publish

on:
  push:
    branches:
      - main
jobs:
  test_and_publish:
    name: Test and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build test
        run: yarn build

      - name: Unit tests
        run: yarn test

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload code coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Create GitHub Release
        uses: zendesk/action-create-release@v1
        id: release
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
