name: codecov
on:
  push:
    branches:
      - main
jobs:
  tests:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Build test
        run: yarn build
      - name: Unit tests
        run: yarn test
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: Publish and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: justincy/github-action-npm-release@latest
        id: release
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          create_tag: 'true'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
          publish_command: 'yarn'
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
